package net.afnf.blog.domain;

import java.util.Date;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class Comment {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column comments.id
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column comments.entryid
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    private Integer entryid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column comments.replyto
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    private Integer replyto;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column comments.name
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    @NotEmpty
    @Length(min = 2, max = 100)
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column comments.content
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    @NotEmpty
    @Length(min = 2, max = 2000)
    private String content;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column comments.postdate
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    private Date postdate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column comments.clientinfo
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    private String clientinfo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column comments.state
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    private Short state;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column comments.id
     * @return  the value of comments.id
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column comments.id
     * @param id  the value for comments.id
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column comments.entryid
     * @return  the value of comments.entryid
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public Integer getEntryid() {
        return entryid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column comments.entryid
     * @param entryid  the value for comments.entryid
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void setEntryid(Integer entryid) {
        this.entryid = entryid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column comments.replyto
     * @return  the value of comments.replyto
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public Integer getReplyto() {
        return replyto;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column comments.replyto
     * @param replyto  the value for comments.replyto
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void setReplyto(Integer replyto) {
        this.replyto = replyto;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column comments.name
     * @return  the value of comments.name
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column comments.name
     * @param name  the value for comments.name
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column comments.content
     * @return  the value of comments.content
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column comments.content
     * @param content  the value for comments.content
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column comments.postdate
     * @return  the value of comments.postdate
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public Date getPostdate() {
        return postdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column comments.postdate
     * @param postdate  the value for comments.postdate
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void setPostdate(Date postdate) {
        this.postdate = postdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column comments.clientinfo
     * @return  the value of comments.clientinfo
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public String getClientinfo() {
        return clientinfo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column comments.clientinfo
     * @param clientinfo  the value for comments.clientinfo
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void setClientinfo(String clientinfo) {
        this.clientinfo = clientinfo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column comments.state
     * @return  the value of comments.state
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column comments.state
     * @param state  the value for comments.state
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void setState(Short state) {
        this.state = state;
    }
}