package net.afnf.blog.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommentExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public CommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEntryidIsNull() {
            addCriterion("entryid is null");
            return (Criteria) this;
        }

        public Criteria andEntryidIsNotNull() {
            addCriterion("entryid is not null");
            return (Criteria) this;
        }

        public Criteria andEntryidEqualTo(Integer value) {
            addCriterion("entryid =", value, "entryid");
            return (Criteria) this;
        }

        public Criteria andEntryidNotEqualTo(Integer value) {
            addCriterion("entryid <>", value, "entryid");
            return (Criteria) this;
        }

        public Criteria andEntryidGreaterThan(Integer value) {
            addCriterion("entryid >", value, "entryid");
            return (Criteria) this;
        }

        public Criteria andEntryidGreaterThanOrEqualTo(Integer value) {
            addCriterion("entryid >=", value, "entryid");
            return (Criteria) this;
        }

        public Criteria andEntryidLessThan(Integer value) {
            addCriterion("entryid <", value, "entryid");
            return (Criteria) this;
        }

        public Criteria andEntryidLessThanOrEqualTo(Integer value) {
            addCriterion("entryid <=", value, "entryid");
            return (Criteria) this;
        }

        public Criteria andEntryidIn(List<Integer> values) {
            addCriterion("entryid in", values, "entryid");
            return (Criteria) this;
        }

        public Criteria andEntryidNotIn(List<Integer> values) {
            addCriterion("entryid not in", values, "entryid");
            return (Criteria) this;
        }

        public Criteria andEntryidBetween(Integer value1, Integer value2) {
            addCriterion("entryid between", value1, value2, "entryid");
            return (Criteria) this;
        }

        public Criteria andEntryidNotBetween(Integer value1, Integer value2) {
            addCriterion("entryid not between", value1, value2, "entryid");
            return (Criteria) this;
        }

        public Criteria andReplytoIsNull() {
            addCriterion("replyto is null");
            return (Criteria) this;
        }

        public Criteria andReplytoIsNotNull() {
            addCriterion("replyto is not null");
            return (Criteria) this;
        }

        public Criteria andReplytoEqualTo(Integer value) {
            addCriterion("replyto =", value, "replyto");
            return (Criteria) this;
        }

        public Criteria andReplytoNotEqualTo(Integer value) {
            addCriterion("replyto <>", value, "replyto");
            return (Criteria) this;
        }

        public Criteria andReplytoGreaterThan(Integer value) {
            addCriterion("replyto >", value, "replyto");
            return (Criteria) this;
        }

        public Criteria andReplytoGreaterThanOrEqualTo(Integer value) {
            addCriterion("replyto >=", value, "replyto");
            return (Criteria) this;
        }

        public Criteria andReplytoLessThan(Integer value) {
            addCriterion("replyto <", value, "replyto");
            return (Criteria) this;
        }

        public Criteria andReplytoLessThanOrEqualTo(Integer value) {
            addCriterion("replyto <=", value, "replyto");
            return (Criteria) this;
        }

        public Criteria andReplytoIn(List<Integer> values) {
            addCriterion("replyto in", values, "replyto");
            return (Criteria) this;
        }

        public Criteria andReplytoNotIn(List<Integer> values) {
            addCriterion("replyto not in", values, "replyto");
            return (Criteria) this;
        }

        public Criteria andReplytoBetween(Integer value1, Integer value2) {
            addCriterion("replyto between", value1, value2, "replyto");
            return (Criteria) this;
        }

        public Criteria andReplytoNotBetween(Integer value1, Integer value2) {
            addCriterion("replyto not between", value1, value2, "replyto");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andPostdateIsNull() {
            addCriterion("postdate is null");
            return (Criteria) this;
        }

        public Criteria andPostdateIsNotNull() {
            addCriterion("postdate is not null");
            return (Criteria) this;
        }

        public Criteria andPostdateEqualTo(Date value) {
            addCriterion("postdate =", value, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateNotEqualTo(Date value) {
            addCriterion("postdate <>", value, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateGreaterThan(Date value) {
            addCriterion("postdate >", value, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateGreaterThanOrEqualTo(Date value) {
            addCriterion("postdate >=", value, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateLessThan(Date value) {
            addCriterion("postdate <", value, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateLessThanOrEqualTo(Date value) {
            addCriterion("postdate <=", value, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateIn(List<Date> values) {
            addCriterion("postdate in", values, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateNotIn(List<Date> values) {
            addCriterion("postdate not in", values, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateBetween(Date value1, Date value2) {
            addCriterion("postdate between", value1, value2, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateNotBetween(Date value1, Date value2) {
            addCriterion("postdate not between", value1, value2, "postdate");
            return (Criteria) this;
        }

        public Criteria andClientinfoIsNull() {
            addCriterion("clientinfo is null");
            return (Criteria) this;
        }

        public Criteria andClientinfoIsNotNull() {
            addCriterion("clientinfo is not null");
            return (Criteria) this;
        }

        public Criteria andClientinfoEqualTo(String value) {
            addCriterion("clientinfo =", value, "clientinfo");
            return (Criteria) this;
        }

        public Criteria andClientinfoNotEqualTo(String value) {
            addCriterion("clientinfo <>", value, "clientinfo");
            return (Criteria) this;
        }

        public Criteria andClientinfoGreaterThan(String value) {
            addCriterion("clientinfo >", value, "clientinfo");
            return (Criteria) this;
        }

        public Criteria andClientinfoGreaterThanOrEqualTo(String value) {
            addCriterion("clientinfo >=", value, "clientinfo");
            return (Criteria) this;
        }

        public Criteria andClientinfoLessThan(String value) {
            addCriterion("clientinfo <", value, "clientinfo");
            return (Criteria) this;
        }

        public Criteria andClientinfoLessThanOrEqualTo(String value) {
            addCriterion("clientinfo <=", value, "clientinfo");
            return (Criteria) this;
        }

        public Criteria andClientinfoLike(String value) {
            addCriterion("clientinfo like", value, "clientinfo");
            return (Criteria) this;
        }

        public Criteria andClientinfoNotLike(String value) {
            addCriterion("clientinfo not like", value, "clientinfo");
            return (Criteria) this;
        }

        public Criteria andClientinfoIn(List<String> values) {
            addCriterion("clientinfo in", values, "clientinfo");
            return (Criteria) this;
        }

        public Criteria andClientinfoNotIn(List<String> values) {
            addCriterion("clientinfo not in", values, "clientinfo");
            return (Criteria) this;
        }

        public Criteria andClientinfoBetween(String value1, String value2) {
            addCriterion("clientinfo between", value1, value2, "clientinfo");
            return (Criteria) this;
        }

        public Criteria andClientinfoNotBetween(String value1, String value2) {
            addCriterion("clientinfo not between", value1, value2, "clientinfo");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Short value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Short value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Short value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Short value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Short value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Short value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Short> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Short> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Short value1, Short value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Short value1, Short value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table comments
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            }
            else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 29 21:20:33 JST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}