package net.afnf.blog.domain;

import java.util.Date;
import java.util.List;

import net.afnf.blog.common.AfnfUtil;

import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.NotEmpty;

public class Entry {

    // //////////////////////////////////////////////////////////////////////

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column entries.id
     * 
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column entries.title
     * 
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    @NotEmpty
    @Length(min = 2)
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column entries.tags
     * 
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    private String tags;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column entries.content
     * 
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    @NotEmpty
    @Length(min = 2)
    private String content;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column entries.content_html
     * 
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    private String contentHtml;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column entries.postdate
     * 
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    private Date postdate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column entries.state
     * 
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    private Short state;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column entries.id
     * 
     * @return the value of entries.id
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column entries.id
     * 
     * @param id the value for entries.id
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column entries.title
     * 
     * @return the value of entries.title
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column entries.title
     * 
     * @param title the value for entries.title
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column entries.tags
     * 
     * @return the value of entries.tags
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column entries.tags
     * 
     * @param tags the value for entries.tags
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column entries.content
     * 
     * @return the value of entries.content
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column entries.content
     * 
     * @param content the value for entries.content
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column entries.content_html
     * 
     * @return the value of entries.content_html
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    public String getContentHtml() {
        return contentHtml;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column entries.content_html
     * 
     * @param contentHtml the value for entries.content_html
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    public void setContentHtml(String contentHtml) {
        this.contentHtml = contentHtml;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column entries.postdate
     * 
     * @return the value of entries.postdate
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    public Date getPostdate() {
        return postdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column entries.postdate
     * 
     * @param postdate the value for entries.postdate
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    public void setPostdate(Date postdate) {
        this.postdate = postdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column entries.state
     * 
     * @return the value of entries.state
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column entries.state
     * 
     * @param state the value for entries.state
     * @mbggenerated Tue Dec 31 19:53:25 JST 2013
     */
    public void setState(Short state) {
        this.state = state;
    }

    private int commentCount = 0;

    public int getCommentCount() {
        return commentCount;
    }

    public void setCommentCount(int commentCount) {
        this.commentCount = commentCount;
    }

    public List<String> getTagList() {
        return AfnfUtil.getTagList(tags);
    }

}
