package net.afnf.blog.domain;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class User {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.id
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.username
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    @NotEmpty
    @Length(min = 4)
    private String username;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.password
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    @NotEmpty
    @Length(min = 4)
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.role
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.id
     * @return  the value of users.id
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.id
     * @param id  the value for users.id
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.username
     * @return  the value of users.username
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.username
     * @param username  the value for users.username
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.password
     * @return  the value of users.password
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.password
     * @param password  the value for users.password
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.role
     * @return  the value of users.role
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.role
     * @param role  the value for users.role
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    public void setRole(String role) {
        this.role = role;
    }
}