package net.afnf.blog.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import net.afnf.blog.domain.Entry;
import net.afnf.blog.domain.EntryExample;

@Mapper
public interface EntryMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table entries
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    int countByExample(EntryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table entries
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    int deleteByExample(EntryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table entries
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table entries
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    int insert(Entry record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table entries
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    int insertSelective(Entry record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table entries
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    List<Entry> selectByExample(EntryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table entries
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    Entry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table entries
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    int updateByExampleSelective(@Param("record") Entry record, @Param("example") EntryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table entries
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    int updateByExample(@Param("record") Entry record, @Param("example") EntryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table entries
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    int updateByPrimaryKeySelective(Entry record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table entries
     * @mbggenerated  Tue Dec 31 19:53:25 JST 2013
     */
    int updateByPrimaryKey(Entry record);
}